version: 2

python:
   install:
   - requirements: requirements.txt

version: 2
sphinx:
  # Path to Sphinx configuration file.
  configuration: conf.py
build:
   os: "ubuntu-22.04"
   tools:
      python: "3.11"
